'use client'
import Cart from '@/components/cart/Cart'
import './globals.css'
import Header from '@/components/layout/heders/Header'
import CartContex from '@/context/cartContext/CartContex'

import { Inter } from 'next/font/google'
import { useContext, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const [isShowCart, setIsShowCart] = useState(false)

  const showCart = () => {
    setIsShowCart(true)
  }
  const hideCart = () => {
    setIsShowCart(false)
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContex>
          <div className='container'>
            {isShowCart ? <Cart onHideCart={hideCart} /> : ''}
            <Header onShowCart={showCart} />
            {children}
            <section className='footer'>

            </section>
          </div>
        </CartContex>
      </body>
    </html>
  )
}
